{% set name = "python-dotenv" %}
{% set version = "0.10.2" %}
{% set sha256 = "6640acd76e6cab84648e4fec16c9d19de6700971f9d91d045e7120622167bfda" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - dotenv = dotenv:cli.cli

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - click >=5.0

test:
  imports:
    - dotenv

about:
  home: https://github.com/theskumar/python-dotenv/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Get and set values in your .env file in local and production servers like Heroku does.'
  dev_url: https://github.com/theskumar/python-dotenv/

extra:
  recipe-maintainers:
    - proinsias
