travis:
  secure:
    BINSTAR_TOKEN: LcQx/Z9EQ1fIXeTlebFeVKMVtg2LBhhHY6L8qxzO6mca4L7duAGSR0cfJ+iuBun4nQxKet86c4b126N5+B7VQt4UZ2D4WvT8rDs/qM0/+N5+HmJ82IkqvGztmDK1dF5ajZtKLesUF8VCYyHn6UyAm+rxLtR2X2pRG6oOesK1Rm4T0hpC4xZzYLrAx9wIeo5JHCc3jkkQkZq0cnOuLgZL0hQap+PuF5yz0BQ/0mUz5BhJoU5vU5yTYRf/yy0xF/p//4ZO5FsyNmBUjQ0AIMbZnAf2ss+itTToIL0z0QxbycnvLY0XrW70xqewoT3+YRmWlrlrjlO1ukn2h2CMQNBm2wfgmQQDb4UHtRLJ7DXiOy9Z3zNAWCzLMcNZCYnqFzepdEOgsKz744YvQBcHjtlH/jLoIjShLInyq56JC8CNE1uZ1haLEkKhK9giPr3zswaIXhXkB6dCGWuJaDp96mMyTYUBasCEWc5ugefnwQeSsDg2N1N20EhiZrHYjmxgZBcFcA8UQ0UXn+P4IgvNADEid4btoHc9S6C0eS+aYEtGAp18dQIw4vmOmOi5asT2U5U1H/DsA5+ZlXTOKnUwuRLWGD4kipqCervsQi8m+N41BLXP5sp0Wu8LyNtwI3I4oa+L2eyejCwZxN0v5iDXNCriPoN3clj/il763MnTLQkkPVg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
