travis:
  secure:
    BINSTAR_TOKEN: mRIGPEQiK2BNl9zraDybuZPK7WciD8BChDnj+NROso9ZYCIDvJbpYTVEz12wN3hGYyixnAUEg3We2cfJVbWlGzgmsY0xSbKApLfIwVXgg8+Cw6y5xPGagZpkkabgLDy6hFHfs3pVcEcL91gaEdPM4UUHqdOz/7RVdEz1spoJSJj9fbJGeW9HmlJPxjoHs0Tw8IxXOs35AIh2luRCDzP3ADNaobXnocgWHxaSUNdRysSWdeWP3Kge2sxivjczSvFcpF1r5kyKxqeiRD94IWtKWRrfc7SBW7QA2Y9HgAYBRJ2OucMzLEn69OUmsB9Ggw2iLql67tRuC2ZXhljL46WNR0Pryux9m3sllFu1d0Tk8ioGSBAn1nP7OLOwv5gXRr75oLpo8W+tkeQRHBK522VTMugQztoh1PGnWVwmm3OBpqHUhvIYP9UlZwDrxV/tjEnRk5nL8IDKmiTtFcVrmK5TdMCNwBiwF6wTlSgz0sE92+KKXftog7QcJx73ZNWvo9iS0SFhH09Q+flXM1PZWyV17CY3ri6EbgcgkB4YrR0sqUhJlTUFYEh93hXvio/0vwcrhoLvsvbBFagY50muoifXBXVqXasufaTZDY2oNCepcgDYpOj5yJ9O3PzKZESPn9hXS5YOV7QT6bf8GbDDruQquMF0JByh8qwsbuspuzHGwN4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
