travis:
  secure:
    BINSTAR_TOKEN: A5MZDCKhbmrZe7rRqxR0jUcJAnnygwJ6MDPeQoBds68DIPFkX5+fBdMHbXFBFfYBZ/FQfwl0wjXccfiAPGBxZ8HdPCzn2KrMQjUv0UbZXvSme8h5KgcDG0iuuX1grSPCNivbfNApqoopoyiT+z01rF5DUaCbl+9xsB2y0T0ggY0s3iG0xHoeutYaZqnUol+V3Sf3tRgzmbNBGWyTTF1KIpNyPmJFZcG9bDEPRPqlaaBlkO1VkW3PW/RPsmfd+4cgBegWlXYZY9QU989AkkA5dUVMayVOVAcGpYtH3HMb/PPFt2iOs6/GwGpyI3yEKKqULYGDYySBzThOQAgAk7OmC+yq0K99FO63P4GGEtFsYkW4M5fhC4HitEEv6GvCzI0EGsmmX+1M5LDUk3q80h0sqIFJ8AdddSIvjbiOkt683GfnRvASS4+Y8MVMemDd5uXsOEhOjFOOEXd9/1gEmjaWF8K32J8vsp7/zimA9pjM1obTf9TFUrq3kfUYCPQQV1kPDSw5cFeRN4ME3Vs3EFHoF54aU82ZVJoWTxdGO+WRSKSB72rqTLQOQxSKMnD9RtybDaf/iUXnGCMKQ/T/LOiB0Di2TSuX/MNqslX7deD1Wc52CYf7v3TMqQasdGoMaZmSa43eXxh8WFpZVq3LsROlvEsfR39PtO9eKzVRrmcTC7I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
